import { defineCommand } from 'citty';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { createLogger } from '@carbon/core';
import { createDefaultParserRegistry, createParserContext, type ParserInput } from '@carbon/parser';
import type { EndpointDef, IntermediateRepresentation } from '@carbon/types';
import { ui } from '../ui.js';

/**
 * `carbon generate-tests --spec <file> --out tests/` — parse a spec into IR
 * and emit one vitest skeleton per endpoint. The output is intentionally
 * minimal: it boots a Carbon replica with `carbon.emulate`, makes the request
 * against the endpoint's declared status, and asserts the response shape.
 * Everything else is a TODO for the author.
 */
export const generateTestsCommand = defineCommand({
  meta: {
    name: 'generate-tests',
    description: 'Generate vitest test skeletons from an ingested spec.',
  },
  args: {
    spec: { type: 'string', description: 'Path or URL of the spec', required: true },
    out: { type: 'string', description: 'Output directory (default: tests/)', default: 'tests' },
  },
  async run({ args }) {
    const logger = createLogger({ level: 'info', pretty: true, name: 'generate-tests' });
    const parsers = createDefaultParserRegistry();
    const input = await load(args.spec as string);
    const ir = await parsers.parse(input, createParserContext(logger, args.spec as string));

    const outDir = resolve(process.cwd(), args.out as string);
    await mkdir(outDir, { recursive: true });

    const specPath = resolve(process.cwd(), args.spec as string);
    let written = 0;
    for (const endpoint of ir.endpoints) {
      const filePath = join(outDir, `${slugify(endpoint)}.test.ts`);
      await mkdir(dirname(filePath), { recursive: true });
      await writeFile(filePath, renderTest(ir, endpoint, specPath), 'utf8');
      written++;
    }

    ui.success(`Wrote ${written} test file${written === 1 ? '' : 's'} to ${outDir}`);
  },
});

async function load(source: string): Promise<ParserInput> {
  if (/^https?:\/\//.test(source)) {
    const res = await fetch(source);
    const text = await res.text();
    try {
      return { kind: 'json', content: JSON.parse(text) };
    } catch {
      return { kind: 'text', content: text };
    }
  }
  const text = await readFile(source, 'utf8');
  try {
    return { kind: 'json', content: JSON.parse(text) };
  } catch {
    return { kind: 'text', content: text };
  }
}

function slugify(endpoint: EndpointDef): string {
  const path = endpoint.path
    .replace(/^\//, '')
    .replace(/\{([^}]+)\}/g, '_$1_')
    .replace(/[^A-Za-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .toLowerCase();
  return `${endpoint.method.toLowerCase()}-${path || 'root'}`;
}

function renderTest(
  ir: IntermediateRepresentation,
  endpoint: EndpointDef,
  specPath: string,
): string {
  const primaryStatus = endpoint.responses[0]?.status ?? 200;
  const pathParams = endpoint.params.filter((p) => p.in === 'path');
  const concretePath = pathParams.reduce(
    (acc, p) => acc.replace(`{${p.name}}`, exampleValue(p.name)),
    endpoint.path,
  );
  const hasBody = ['POST', 'PUT', 'PATCH'].includes(endpoint.method);
  const bodyLiteral = hasBody ? '{}' : 'undefined';

  return `// Generated by \`carbon generate-tests\` for ${ir.api.name} v${ir.api.version}.
// Endpoint: ${endpoint.method} ${endpoint.path}
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { carbon, type Replica } from '@carbon/sdk';

describe('${endpoint.method} ${endpoint.path}', () => {
  let replica: Replica;

  beforeAll(async () => {
    replica = await carbon.emulate({ from: ${JSON.stringify(specPath)}, port: 0 });
  });

  afterAll(async () => {
    await replica.close();
  });

  it('responds with ${primaryStatus}', async () => {
    const url = \`\${replica.url}${concretePath}\`;
    const init: RequestInit = { method: '${endpoint.method}' };
    const body = ${bodyLiteral};
    if (body !== undefined) {
      init.headers = { 'content-type': 'application/json' };
      init.body = JSON.stringify(body);
    }
    const res = await fetch(url, init);
    expect(res.status).toBe(${primaryStatus});
    // TODO: assert response shape / persisted state.
  });
});
`;
}

function exampleValue(name: string): string {
  if (/id$/i.test(name)) return '1';
  return 'example';
}
