import { defineCommand } from 'citty';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { createLogger } from '@carbon/core';
import { createDefaultParserRegistry, createParserContext, type ParserInput } from '@carbon/parser';
import type { EndpointDef, IntermediateRepresentation } from '@carbon/types';
import { orderForSmoke } from './test.js';
import { ui } from '../ui.js';

/**
 * `carbon generate-tests --spec <file> --out tests/` — parse a spec into IR
 * and emit a single, runnable vitest file. Unlike the old per-endpoint
 * skeletons (which just asserted a status and left a `// TODO`), the emitted
 * suite boots ONE shared replica and exercises every endpoint in stateful
 * order: creates mint ids that the following reads/updates/deletes reuse, and
 * list responses are checked for the created record. The output is a starter —
 * developers are expected to tighten schema assertions and add fixtures — but
 * it is correct enough to run green against a spec whose declared statuses
 * match what the runtime serves.
 */
export const generateTestsCommand = defineCommand({
  meta: {
    name: 'generate-tests',
    description: 'Generate a runnable, stateful vitest suite from an ingested spec.',
  },
  args: {
    spec: { type: 'string', description: 'Path or URL of the spec', required: true },
    out: { type: 'string', description: 'Output directory (default: tests/)', default: 'tests' },
  },
  async run({ args }) {
    const logger = createLogger({ level: 'info', pretty: true, name: 'generate-tests' });
    const parsers = createDefaultParserRegistry();
    const input = await load(args.spec as string);
    const ir = await parsers.parse(input, createParserContext(logger, args.spec as string));

    const outDir = resolve(process.cwd(), args.out as string);
    await mkdir(outDir, { recursive: true });

    const specPath = resolve(process.cwd(), args.spec as string);
    const filePath = join(outDir, `${fileSlug(ir)}.test.ts`);
    await mkdir(dirname(filePath), { recursive: true });
    await writeFile(filePath, renderTestFile(ir, specPath), 'utf8');

    ui.success(`Wrote ${filePath} (${ir.endpoints.length} endpoints in stateful order)`);
  },
});

async function load(source: string): Promise<ParserInput> {
  if (/^https?:\/\//.test(source)) {
    const res = await fetch(source);
    const text = await res.text();
    try {
      return { kind: 'json', content: JSON.parse(text) };
    } catch {
      return { kind: 'text', content: text };
    }
  }
  const text = await readFile(source, 'utf8');
  try {
    return { kind: 'json', content: JSON.parse(text) };
  } catch {
    return { kind: 'text', content: text };
  }
}

/**
 * Render a self-contained vitest file. Pure and exported so the generator's
 * output can be unit-tested without touching the filesystem.
 */
export function renderTestFile(ir: IntermediateRepresentation, specPath: string): string {
  const ordered = orderForSmoke(ir.endpoints);
  const plan = ordered.map(renderPlanEntry);
  const title = `${ir.api.name} v${ir.api.version}`;

  return `// Generated by \`carbon generate-tests\` — ${title}.
// One shared replica runs the whole suite in order, so creates are visible
// to the reads that follow. Re-run \`carbon generate-tests --spec <spec>\`
// to regenerate (your edits will be overwritten).
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { carbon, type Replica } from '@carbon/sdk';

const SPEC = ${JSON.stringify(specPath)};

// Compact endpoint plan derived from the spec's normalized IR. \`expected\` is
// the set of status codes the spec declares for the endpoint; \`body\` is the
// request-body schema (null when the method has no body).
type Schema =
  | { kind: 'string'; format?: string; enum?: readonly string[] }
  | { kind: 'number' | 'integer' | 'boolean' | 'null'; format?: string }
  | { kind: 'array'; items: Schema }
  | { kind: 'object'; properties: Record<string, Schema>; required: readonly string[] }
  | { kind: 'ref'; ref: string }
  | { kind: 'union'; anyOf: readonly Schema[] }
  | { kind: 'unknown' };

interface Step {
  method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'HEAD' | 'OPTIONS';
  path: string;
  operation: 'list' | 'get' | 'create' | 'update' | 'replace' | 'delete' | 'action' | 'custom';
  resource: string | null;
  expected: number[];
  body: Schema | null;
}

const plan: Step[] = [
${plan.join(',\n')}
];

/** Build a representative request body from a normalized schema. */
function sampleValue(schema: Schema | null): unknown {
  if (!schema) return {};
  switch (schema.kind) {
    case 'string':
      return schema.enum?.[0] ?? (schema.format === 'email' ? 'carbon@example.com' : 'example');
    case 'number':
    case 'integer':
      return 1;
    case 'boolean':
      return true;
    case 'null':
      return null;
    case 'array':
      return [sampleValue(schema.items)];
    case 'object': {
      const out: Record<string, unknown> = {};
      for (const name of schema.required ?? []) out[name] = sampleValue(schema.properties?.[name] ?? null);
      return out;
    }
    case 'union':
      return sampleValue(schema.anyOf[0] ?? null);
    case 'ref':
    case 'unknown':
      return {};
  }
}

/** Substitute path params, preferring a previously-created resource id. */
function buildPath(step: Step, ids: Map<string, string>): string {
  return step.path.replace(/\\{([^/}]+)\\}/g, (_match, name: string) => {
    if (step.resource) {
      const id = ids.get(step.resource);
      if (id) return id;
    }
    return /(^|_)id$/i.test(name) ? '1' : 'example';
  });
}

describe(${JSON.stringify(title)}, () => {
  let replica: Replica;
  const ids = new Map<string, string>();

  beforeAll(async () => {
    replica = await carbon.emulate({ from: SPEC, port: 0 });
  });

  afterAll(async () => {
    await replica.close();
  });

  for (const step of plan) {
    it(\`\${step.method} \${step.path}\`, async () => {
      const path = buildPath(step, ids);
      const hasBody = ['POST', 'PUT', 'PATCH'].includes(step.method);
      const res = await fetch(\`\${replica.url}\${path}\`, {
        method: step.method,
        headers: hasBody ? { 'content-type': 'application/json' } : undefined,
        body: hasBody ? JSON.stringify(sampleValue(step.body)) : undefined,
      });

      if (step.expected.length > 0) {
        expect(step.expected).toContain(res.status);
      } else {
        expect(res.status).toBeLessThan(400);
      }

      const text = await res.text();
      let body: unknown = null;
      if (text) {
        try {
          body = JSON.parse(text);
        } catch {
          body = text;
        }
      }

      // A successful create mints an id the following GET/PATCH/DELETE reuse.
      if (step.operation === 'create' && step.resource && body && typeof body === 'object') {
        const id = (body as Record<string, unknown>).id;
        if (typeof id === 'string' && id.length > 0) ids.set(step.resource, id);
      }

      // For list endpoints, confirm the record we created earlier is visible —
      // this is the stateful behavior that distinguishes Carbon from a stub.
      if (step.operation === 'list' && step.resource && ids.has(step.resource) && body) {
        const rows = Array.isArray(body)
          ? body
          : typeof body === 'object' && Array.isArray((body as { data?: unknown }).data)
            ? ((body as { data: unknown[] }).data as unknown[])
            : null;
        if (rows) {
          const id = ids.get(step.resource);
          expect(
            rows.some(
              (row) =>
                typeof row === 'object' && row !== null && (row as Record<string, unknown>).id === id,
            ),
          ).toBe(true);
        }
      }
    });
  }
});
`;
}

function renderPlanEntry(endpoint: EndpointDef): string {
  const expected = endpoint.responses.map((response) => response.status);
  const body = endpoint.requestBody ? JSON.stringify(endpoint.requestBody) : 'null';
  return [
    '  {',
    `    method: ${JSON.stringify(endpoint.method)},`,
    `    path: ${JSON.stringify(endpoint.path)},`,
    `    operation: ${JSON.stringify(endpoint.operation)},`,
    `    resource: ${JSON.stringify(endpoint.resource)},`,
    `    expected: ${JSON.stringify(expected)},`,
    `    body: ${body},`,
    '  }',
  ].join('\n');
}

function fileSlug(ir: IntermediateRepresentation): string {
  const base = ir.api.name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
  return base || 'api';
}
