packages:
  - 'apps/*'
  - 'packages/*'
  - 'benchmarks'
  - 'examples/*'
allowBuilds:
  '@firebase/util': true
  '@scarf/scarf': false
  '@vscode/vsce-sign': false
  esbuild: false
  keytar: false
  msgpackr-extract: false
  protobufjs: true
  puppeteer: false
  sharp: true
