# Grafana datasources auto-loaded on boot.
# See https://grafana.com/docs/grafana/latest/administration/provisioning/#datasources
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: carbon-prometheus
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s
      httpMethod: POST

  - name: Tempo
    type: tempo
    access: proxy
    uid: carbon-tempo
    url: http://tempo:3200
    editable: true
    jsonData:
      httpMethod: GET
      tracesToLogsV2:
        datasourceUid: carbon-prometheus
      serviceMap:
        datasourceUid: carbon-prometheus
      nodeGraph:
        enabled: true
